FIX 📍 "error: operator does not exist: json @> json"
devlopersabbir/find-devs pull request #19
Opened 2024-03-18 18:31 UTC by maxlshk

Sorry for the late update, I resolved the issue with @> operator:

![image](https://github.com/devlopersabbir/find-devs/assets/119050285/17b5f898-aca8-408f-ac42-c5177792b33a)

**The problem turned out to be not in my code, but rather in the format of "skills" column in your DB.**
After few attempts of resolving the error while using `arrayContains` I kept receiving the  (SQLSTATE 42883 error), which was caused by data being in JSON and not JSONB format, which didn't support operations like `arrayContains` at all.

The only clear solution solution is to cast the JSON column to JSONB for the purpose of this operation and it turned out to be a success.

![image](https://github.com/devlopersabbir/find-devs/assets/119050285/3b0af476-3e8e-4345-a3ba-1562c6357f1f)
![image](https://github.com/devlopersabbir/find-devs/assets/119050285/60676729-65f9-40d3-bda5-a235efd9c26a)

I've tested it on my local data and it seems to be working well. I used similar queries, that are used in drizzle's `arrayContains` and not `ilike`, so only full convergency of the skill will show results. If there are any issues on your end please inform me 😉

2024-03-18 18:34 UTC, maxlshk commented
And yeah, I send pull request not into your main branch so that you won't need to revert changes in case there are any issues.

2024-03-27 19:45 UTC, devlopersabbir commented
@maxlshk sorry for mentioning to you.
But I think you should take care of this issue that I make comments

2024-03-27 20:44 UTC, maxlshk commented
> @maxlshk sorry for mentioning to you. But I think you should take care of this issue that I make comments

Hey, @devlopersabbir I'd gladly examine your comments, but it looks like your review is still pending:
![image](https://github.com/devlopersabbir/find-devs/assets/119050285/c45ef021-d7b4-4d61-842f-89e5ceed31e0)
Maybe you forgot to submit it, so please make sure I can see it 🤓

2024-03-28 22:58 UTC, devlopersabbir requested changes
Just add make changes with awesome commit message 😇
I'll be happy to marge it :)

2024-03-28 22:58 UTC, devlopersabbir commented on src/components/contents/ProfileGrid.tsx
> +  const skillsCondition = searchSkills.length > 0
I really appreciate your passion 🥹
One simple change is needed,
Can you make sure that, if the user types skills like `python` but our db array has `Python` then it should be searched perfectly,

Now, it does not give the result as user expects.

Can we make it whenever you write like all `uppercase` or `lowercase` or `camelcase` anything. so, it should give results perfectly

2024-03-30 12:03 UTC, maxlshk commented on src/components/contents/ProfileGrid.tsx
> +  const skillsCondition = searchSkills.length > 0
Just added a commit, that should resolve the case sensitive search issue. I'm pretty sure now that all inputs and JSON strings from db are converted to lowercase everything should work just fine ✅

2024-03-30 18:05 UTC, devlopersabbir approved these changes
@maxlshk thanks for your latest update 😍

2024-03-30 18:06 UTC, merged